with-expecter: true
filename: "{{.PackageName}}.go"
dir: "."
mockname: "Mock{{ .PackageName | camelcase }}{{.InterfaceName}}"
outpkg: "mocks"
issue-845-fix: True

packages:
  github.com/csnewman/beanbridge/internal/beanstalk:
    interfaces:
      Handler:
